export enum LOCALITE {
    REGION = 'REGION',
    PREFECTURE = 'PREFECTURE',
    COMMUNE = 'COMMUNE',
    QUARTIER = 'QUARTIER',
    SECTEUR = 'SECTEUR'
}
export enum STATUT{
    ACTIVE = 'ACTIVER',
    DESACTIVE = 'DESACTIVE'
  }

export enum OPTION_GET_USER{
    TOUT = 'TOUT',
    REGION = 'REGION',
    PREFECTURE = 'PREFECTURE',
}

export enum PERMISSIONS {
    CAN_VIEW_DASHBORD = 'CAN_VIEW_DASHBOARD',

    // Alerte
    CAN_VIEW_ALERT_MENU = 'CAN_VIEW_ALERT_MENU',
    CAN_VIEW_ALERT_LIST = 'CAN_VIEW_ALERT_LIST',
    CAN_VIEW_ALERT_INFO = 'CAN_VIEW_ALERT_INFO',
    CAN_ADD_ALERT = 'CAN_ADD_ALERT',
    CAN_UPDATE_ALERT = 'CAN_UPDATE_ALERT',
    CAN_DELETE_ALERT = 'CAN_DELETE_ALERT',
    CAN_AFFECTE_ALERT_USER = 'CAN_AFFECT_ALERTE_USER',

    // Cas
    CAN_VIEW_CAS_MENU = 'CAN_VIEW_CAS_MENU',
    CAN_VIEW_CAS_LIST = 'CAN_VIEW_CAS_LIST',
    CAN_VIEW_CAS_INFO = 'CAN_VIEW_CAS_INFO',
    CAN_ADD_CAS = 'CAN_ADD_CAS',
    CAN_UPDATE_CAS = 'CAN_UPDATE_CAS',
    CAN_DELETE_CAS = 'CAN_DELETE_CAS',
    CAN_UPDATE_CAS_STATUS = 'CAN_UPDATE_CAS_STATUS',
    CAN_UPDATE_CAS_RESPONSE = 'CAN_UPDATE_CAS_RESPONSE',
    CAN_DELETE_CAS_TRAITEMENT = 'CAN_DELETE_CAS_TRAITEMENT',

    // ARTICLE 
    CAN_VIEW_ARTICLE_MENU = "CAN_VIEW_ARTICLE_MENU",
    CAN_VIEW_ARTICLE_LIST = "CAN_VIEW_ARTICLE_LIST",
    CAN_VIEW_ARTICLE_INFO = "CAN_VIEW_ARTICLE_INFO",
    CAN_ADD_ARTICLE = "CAN_ADD_ARTICLE",
    CAN_UPDATE_ARTICLE = "CAN_UPDATE_ARTICLE",
    CAN_DELETE_ARTICLE = "CAN_DELETE_ARTICLE", 
    
    // CATEGORIE_ARTICLE
    CAN_VIEW_CATEGORIE_ARTICLE_MENU = "CAN_VIEW_CATEGORIE_ARTICLE_MENU",
    CAN_VIEW_CATEGORIE_ARTICLE_LIST = "CAN_VIEW_CATEGORIE_ARTICLE_LIST",
    CAN_VIEW_CATEGORIE_ARTICLE_INFO = "CAN_VIEW_CATEGORIE_ARTICLE_INFO",
    CAN_ADD_CATEGORIE_ARTICLE = "CAN_ADD_CATEGORIE_ARTICLE",
    CAN_UPDATE_CATEGORIE_ARTICLE = "CAN_UPDATE_CATEGORIE_ARTICLE",
    CAN_DELETE_CATEGORIE_ARTICLE = "CAN_DELETE_CATEGORIE_ARTICLE", 


     // CATEGORIE
     CAN_VIEW_CATEGORIE_MENU = "CAN_VIEW_CATEGORIE_MENU",
     CAN_VIEW_CATEGORIE_LIST = "CAN_VIEW_CATEGORIE_LIST",
     CAN_VIEW_CATEGORIE_INFO = "CAN_VIEW_CATEGORIE_INFO",
     CAN_ADD_CATEGORIE = "CAN_ADD_CATEGORIE",
     CAN_UPDATE_CATEGORIE = "CAN_UPDATE_CATEGORIE",
     CAN_DELETE_CATEGORIE = "CAN_DELETE_CATEGORIE", 

    // Marque
    CAN_VIEW_MARQUE_MENU = "CAN_VIEW_MARQUE_MENU",
    CAN_VIEW_MARQUE_LIST = "CAN_VIEW_MARQUE_LIST",
    CAN_VIEW_MARQUE_INFO = "CAN_VIEW_MARQUE_INFO",
    CAN_ADD_MARQUE = "CAN_ADD_MARQUE",
    CAN_UPDATE_MARQUE = "CAN_UPDATE_MARQUE",
    CAN_DELETE_MARQUE = "CAN_DELETE_MARQUE",

    // Groupement
    CAN_VIEW_GROUPEMENT_MENU = "CAN_VIEW_GROUPEMENT_MENU",
    CAN_VIEW_GROUPEMENT_LIST = "CAN_VIEW_GROUPEMENT_LIST",
    CAN_VIEW_GROUPEMENT_INFO = "CAN_VIEW_GROUPEMENT_INFO",
    CAN_ADD_GROUPEMENT = "CAN_ADD_GROUPEMENT",
    CAN_UPDATE_GROUPEMENT = "CAN_UPDATE_GROUPEMENT",
    CAN_DELETE_GROUPEMENT = "CAN_DELETE_GROUPEMENT",
    

    // Utilisateur
    CAN_VIEW_USER_MENU = 'CAN_VIEW_USER_MENU',
    CAN_VIEW_USERS_LIST = 'CAN_VIEW_USER_LIST',
    CAN_VIEW_USER_INFO = 'CAN_VIEW_USER_INFO',
    CAN_ADD_USER = 'CAN_ADD_USER',
    CAN_UPDATE_USER = 'CAN_UPDATE_USER',
    CAN_DELETE_USER = 'CAN_DELETE_USER',

    // Role
    CAN_VIEW_ROLE_MENU = 'CAN_VIEW_ROLE_MENU',
    CAN_VIEW_ROLES_LIST = 'CAN_VIEW_ROLE_LIST',
    CAN_VIEW_ROLE_INFO = 'CAN_VIEW_ROLE_INFO',
    CAN_ADD_ROLE = 'CAN_ADD_ROLE',
    CAN_UPDATE_ROLE = 'CAN_UPDATE_ROLE',
    CAN_DELETE_ROLE = 'CAN_DELETE_ROLE',


    // TYPE_CAS
    CAN_VIEW_TYPE_CAS_MENU = 'CAN_VIEW_TYPE_CAS_MENU',
    CAN_VIEW_TYPE_CAS_LIST = 'CAN_VIEW_TYPE_CAS_LIST',
    CAN_VIEW_TYPE_CAS_INFO = 'CAN_VIEW_TYPE_CAS_INFO',
    CAN_ADD_TYPE_CAS = 'CAN_ADD_TYPE_CAS',
    CAN_UPDATE_TYPE_CAS = 'CAN_UPDATE_TYPE_CAS',
    CAN_DELETE_TYPE_CAS = 'CAN_DELETE_TYPE_CAS',

    // PARTENAIRE
    CAN_VIEW_PARTENAIRE_MENU = 'CAN_VIEW_PARTENAIRE_MENU',
    CAN_VIEW_PARTENAIRE_LIST = 'CAN_VIEW_PARTENAIRE_LIST',
    CAN_VIEW_PARTENAIRE_INFO = 'CAN_VIEW_PARTENAIRE_INFO',
    CAN_ADD_PARTENAIRE = 'CAN_ADD_PARTENAIRE',
    CAN_UPDATE_PARTENAIRE = 'CAN_UPDATE_PARTENAIRE',
    CAN_DELETE_PARTENAIRE = 'CAN_DELETE_PARTENAIRE',

    // TYPE_APPUI
    CAN_VIEW_TYPE_APPUI_MENU = 'CAN_VIEW_TYPE_APPUI_MENU',
    CAN_VIEW_TYPE_APPUI_LIST = 'CAN_VIEW_TYPE_APPUI_LIST',
    CAN_VIEW_TYPE_APPUI_INFO = 'CAN_VIEW_TYPE_APPUI_INFO',
    CAN_ADD_TYPE_APPUI = 'CAN_ADD_TYPE_APPUI',
    CAN_UPDATE_TYPE_APPUI = 'CAN_UPDATE_TYPE_APPUI',
    CAN_DELETE_TYPE_APPUI = 'CAN_DELETE_TYPE_APPUI',

    // SURVEILLANCE
    CAN_VIEW_SURVEILLANCE_MENU = 'CAN_VIEW_SURVEILLANCE_MENU',
    CAN_VIEW_SURVEILLANCE_LIST = 'CAN_VIEW_SURVEILLANCE_LIST',
    CAN_VIEW_SURVEILLANCE_INFO = 'CAN_VIEW_SURVEILLANCE_INFO',
    CAN_ADD_SURVEILLANCE = 'CAN_ADD_SURVEILLANCE',
    CAN_UPDATE_SURVEILLANCE = 'CAN_UPDATE_SURVEILLANCE',
    CAN_DELETE_SURVEILLANCE = 'CAN_DELETE_SURVEILLANCE',

    // STATISTIQUE
    CAN_VIEW_STATISTIQUE_MENU = 'CAN_VIEW_STATISTIQUE_MENU',
    CAN_VIEW_STATISTIQUE_LIST = 'CAN_VIEW_STATISTIQUE_LIST',
    CAN_VIEW_STATISTIQUE_INFO = 'CAN_VIEW_STATISTIQUE_INFO',
    CAN_ADD_STATISTIQUE = 'CAN_ADD_STATISTIQUE',
    CAN_UPDATE_STATISTIQUE = 'CAN_UPDATE_STATISTIQUE',
    CAN_DELETE_STATISTIQUE = 'CAN_DELETE_STATISTIQUE',
}

export const DATE_FORMAT = 'yyyy-MM-dd';

export const DISPLAY_DATE_FORMAT = 'dd/MM/yyyy';

export const TEL_PATTERN = /^[0-9]{9}$/;

export const SELECT_NUMBER_PATTERN = /^[1-9][0-9]*$/;

export const SELECT_EMAIL_PATTERN = "^[a-z0-9._%+-]+@[a-z0-9.-]+\\.[a-z]{2,4}$"

export const NUMBER_ONLY_PATTERN = /^[0-9]*$/;

export enum STATUT_ALERTE {
    TRAITE = 'TRAITE',
    NON_TRAITE = 'NON_TRAITE'
}

export enum STATUT_CAS {
    EN_ATTENTE = 'EN_ATTENTE',
    EN_COURS = 'EN_COURS',
    TRAITE = 'TRAITE',
    ANNULE = 'ANNULE'
}
